

CREATE TABLE XE_USUARIO (
ID_USUARIO NUMBER(10) NOT NULL,
NM_USUARIO VARCHAR2(20),
STATUS CHAR(2),
DT_ULT_ACESSO DATE,
PRIMARY KEY (ID_USUARIO)
);

CREATE SEQUENCE USUARIO_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCACHE
NOCYCLE
/

CREATE TABLE XE_PERFIL (
ID_PERFIL NUMBER(10) NOT NULL,
ID_USUARIO NUMBER(10),
NM_PERFIL VARCHAR2(20),
PRIMARY KEY (ID_PERFIL)
);
ALTER TABLE XE_PERFIL ADD CONSTRAINT XE_MODULO_USUARIO_FK
FOREIGN KEY (ID_USUARIO) REFERENCES XE_USUARIO(ID_USUARIO);
/ 

CREATE TABLE XE_MODULO (
ID_MODULO NUMBER(10) NOT NULL,
ID_PERFIL NUMBER(10),
NM_MODULO VARCHAR2(20),
PRIMARY KEY (ID_MODULO)
);
ALTER TABLE XE_MODULO ADD CONSTRAINT XE_MODULO_PERFIL_FK
FOREIGN KEY (ID_PERFIL) REFERENCES XE_PERFIL(ID_PERFIL);
/ 

CREATE TABLE XE_DEPARTAMENTO (
ID_DEPARTAMENTO NUMBER(10) NOT NULL,
ID_USUARIO NUMBER(10),
NM_DEPARTAMENTO VARCHAR2(20),
PRIMARY KEY (ID_DEPARTAMENTO)
);
ALTER TABLE XE_DEPARTAMENTO ADD CONSTRAINT XE_DEPART_USUARIO_FK
FOREIGN KEY (ID_USUARIO) REFERENCES XE_USUARIO(ID_USUARIO);
/ 

