CREATE VIEW USUARIO_VW ("CODIGO","NOME","STATUS","DT_ULT_ACESSO", "DEPARTAMENTO", "MODULO") AS
SELECT 
  U.ID_USUARIO CODIGO,
  U.NM_USUARIO NOME,
  U.STATUS,
  U.DT_ULT_ACESSO,
  D.NM_DEPARTAMENTO DEPARTAMENTO,
  M.NM_MODULO MODULO
FROM
  XE_USUARIO U,
  XE_DEPARTAMENTO D,
  XE_MODULO M,
  XE_PERFIL P
WHERE U.ID_USUARIO = D.ID_USUARIO
  AND U.ID_USUARIO = P.ID_USUARIO
  AND P.ID_PERFIL = M.ID_PERFIL;