CREATE OR REPLACE PACKAGE XE_PCK_TESTE
IS
  FUNCTION VERIFICA_STATUS (P_ID_USUARIO IN NUMBER) RETURN NUMBER;
  PROCEDURE PRINCIPAL (P_TIPO_DML in VARCHAR2, P_NM_USUARIO in VARCHAR2, P_STATUS in VARCHAR2, P_DT_ULT_ACESSO in DATE, P_MENS OUT VARCHAR2);
END;

CREATE OR REPLACE PACKAGE BODY XE_PCK_TESTE
  IS

  CURSOR C_INATIVOS IS
    SELECT
	  NM_USUARIO 
    FROM 
	  XE_USUARIO 
    WHERE 
	  STATUS = 'A' 
    AND TRUNC(SYSDATE - TO_DATE(DT_ULT_ACESSO)) > 60;


-- Veririca de usuário está ativo.
FUNCTION VERIFICA_STATUS(P_ID_USUARIO IN NUMBER) RETURN NUMBER IS

  V_STATUS CHAR(2);

  BEGIN
    SELECT 
	  STATUS 
	INTO V_STATUS
    FROM 
	  XE_USUARIO 
    WHERE 
	  ID_USUARIO = P_ID_USUARIO;

    IF V_STATUS = 'A' THEN
      RETURN(1);
    ELSE 
      RETURN(0);
    END IF;

  END;
  
PROCEDURE INATIVA AS
  
  BEGIN
    FOR R_INA IN C_INATIVOS LOOP
      DELETE FROM XE_USUARIO WHERE NM_USUARIO = R_INA.NM_USUARIO;
    END LOOP;
  END;
  
PROCEDURE PRINCIPAL (P_TIPO_DML IN VARCHAR2, P_NM_USUARIO IN VARCHAR2, P_STATUS IN VARCHAR2, P_DT_ULT_ACESSO IN DATE, P_MENS OUT VARCHAR2) IS

  V_EXISTE VARCHAR2(100);

  BEGIN
  
   -- SE INSERT
  IF P_TIPO_DML = 'I' THEN
      SELECT ID_USUARIO INTO V_EXISTE
      FROM XE_USUARIO
      WHERE NM_USUARIO = P_NM_USUARIO;
  
      IF V_EXISTE > 0 THEN
        P_MENS := 1;
      ELSE
        INSERT INTO XE_USUARIO  VALUES (USUARIO_SEQ.NEXTVAL, P_NM_USUARIO, P_STATUS, SYSDATE);
        P_MENS := 0;
      END IF;
    END IF;
    
    -- SE UPDATE
    IF P_TIPO_DML = 'U' THEN
      SELECT ID_USUARIO INTO V_EXISTE
      FROM XE_USUARIO
      WHERE NM_USUARIO = P_NM_USUARIO;
  
      IF V_EXISTE > 0 THEN
        UPDATE XE_USUARIO SET STATUS = P_STATUS WHERE NM_USUARIO = P_NM_USUARIO;
        P_MENS := 0;
        ELSE 
        P_MENS := 1;
      END IF;
    END IF;
    
      -- SE DELETE
    IF P_TIPO_DML = 'D' THEN
      SELECT ID_USUARIO INTO V_EXISTE
      FROM XE_USUARIO
      WHERE NM_USUARIO = P_NM_USUARIO;
  
      IF V_EXISTE > 0 THEN
        DELETE FROM XE_USUARIO WHERE NM_USUARIO = P_NM_USUARIO;
        P_MENS := 0;
        ELSE
        P_MENS := 1;
      END IF;
    END IF;
    
  END;

END XE_PCK_TESTE;